#!/usr/bin/env bash

# Bash script to configure Nginx server to have a custom 404 page that contains the string `Ceci n'est` pas une page.
# Requirements:

#     1. The page must return an HTTP 404 error code
#     2. The page must contain the string `Ceci n'est pas une` page
#     3. Using what you did with `3-redirection`, write `4-not_found_page_404` so that it configures
#	  a brand new Ubuntu machine to the requirements asked in this task
