#!/usr/bin/env bash
# Bash script to configure Nginx server to have a custom 404 page
# that contains the string `Ceci n'est` pas une page.
# Requirements:
#     1. The page must return an HTTP 404 error code
#     2. The page must contain the string `Ceci n'est pas une` page
#     3. Using what you did with `3-redirection`, write `4-not_found_page_404` so that it configures
#	  a brand new Ubuntu machine to the requirements asked in this task

apt-get -y update
apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
        listen 80;
        listen [::]:80 default_server;
                
        root /var/www/html/;
        index index.html index.htm index.html-debian.html;
                
        location /redirect_me{
            return 301 https://www.github.com/belovetech;
        }
        
        error_page 404 /404.html;
        location /404{
            root /var/www/html/;
            internal;
        }    
    
}" > /etc/nginx/sites-available/default

service nginx restart
