#!/usr/bin/env bash
# The goal here is to be able to track which web server is answering our
# HTTP requests, to understand and track the way a load balancer works.
# More in the coming tasks.
# Requirements:
#   * Configure Nginx so that its HTTP response contains
#		 a custom header (on `web-01` and `web-02`)
#      - The name of the custom HTTP header must be `X-Served-By`
#      - The value of the custom HTTP header must be the hostname
#		 of the server Nginx is running on
#   * Write 0-custom_http_response_header so that it configures a brand
#      new Ubuntu machine to the requirements asked in this task
#      - `Ignore SC2154` for `shellcheck`


apt-get -y update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
printf %s "server {
        listen 80;
        listen [::]:80 default_server;

		add_header X-Served-By $HOSTNAME;

        root /etc/nginx/html/;
        index index.html index.htm index.html-debian.html;
                
        location /redirect_me{
            return 301 https://www.google.com/;
        }
        
        error_page 404 /404.html;
        location /404{
            root /etc/nginx/html/;
            internal;
        }    
    
}" > /etc/nginx/sites-available/default

service nginx restart