#!/usr/bin/env bash
# Bash script that configures the container to nginx must be running as nginx user, and nginx must be listening on all active IPs on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart"
